# Site settings
title: goop.nu
email: joel[at]goop.nu
author: Joel Goop
description: > # this means to ignore newlines until "baseurl:"
  My personal website where I post about projects and useful stuff. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://goop.nu"
github_username:  joelgoop

# Content
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Build settings
markdown: kramdown
excerpt_separator: <!--end excerpt-->
