- hosts: all
  tasks:

    - name: Copy config files
      copy: src={{item.file}} dest={{item.path}}
      with_items:
        - {file: '.bashrc', path: '~/.bashrc'}

    - name: Update apt
      sudo: true
      apt: update_cache=yes

    - name: Install packages
      sudo: true
      apt: pkg={{ item }} state=installed
      with_items:
        - ruby-dev
        - nodejs

    - name: Install Jekyll
      sudo: true
      gem: name=jekyll state=present user_install=no