- name: Copy files
  copy: src={{item.file}} dest={{item.path}}
  with_items:
    - {file: 'goopsite.sh', path: '~/goopsite.sh'}
    - {file: '/vagrant/deploy/id_rsa', path: "{{deploy_key}}"}

- name: Set script permissions
  file: path={{ item.path }} mode={{ item.mode }}
  with_items:
    - {path: '~/goopsite.sh', mode: 755}
    - {path: "{{deploy_key}}", mode: 700}

- name: Environment variables
  lineinfile: dest=~/.bashrc state=present line="export {{item.name}}={{item.value}}"
  with_items:
    - {name: "SITE_SRC", value: "~/src"}
    - {name: "DEPLOY_KEY", value: "{{ deploy_key }}"}

- name: Aliases
  lineinfile: dest=~/.bashrc state=present line="alias {{item.name}}={{item.value}}"
  with_items:
    - {name: "goopsite", value: "~/goopsite.sh"}

- name: Update apt
  sudo: true
  apt: update_cache=yes

- name: Install packages
  sudo: true
  apt: pkg={{ item }} state=installed
  with_items:
    - ruby-dev
    - nodejs

- name: Install Jekyll
  sudo: true
  gem: name=jekyll state=present user_install=no