- name: Install git (for bower)
  sudo: yes
  apt: name=git state=present

- name: Set ownership on /usr/local/
  sudo: yes
  shell: chown -R vagrant /usr/local/

- name: Tell npm to use /usr/local
  command: npm config set prefix "/usr/local"

- name: Install global Node.js packages
  npm: state=present global=yes name={{item}}
  with_items:
      - gulp
      - bower

# - name: Install some Ruby gems
#   sudo: yes
#   gem: name={{item}} state=present user_install=no
#   with_items:
#       - sass

- name: Symlink package.json for npm dev dependencies
  file: src={{ frontend_dir }}/package.json dest=~/package.json state=link

- name: Install Node.js packages for design stuff
  command: chdir=~/ npm install

- name: Install Bower packages for design stuff
  command: chdir={{ frontend_dir }} bower install

# - name: Run gulp to provide front-end dependencies
#   command: chdir={{ frontend_dir }} gulp all